### ISSUE TITLE
你的python写的软件没有打包

### ISSUE THREAD

**Issue by 2439905184** [lzr2006/lzr2006.github.io#3]
对于不同开发者的电脑，python版本不一样，装的开发库不一样，直接发布源码去运行，可能会运行不了（对于普通用户）
建议用打包工具打包一下 你可以研究下pyinstaller这个打包工具，可以打包成exe（这样即使用户电脑没有python环境也能运行）
还有，readme文件也可以写详细一点，写运行源码需要安装哪些必备的库。
我看了一下，运行报错，缺少库。
但是我觉得安装麻烦，就没去解决问题，因为同时还在搞自己的东西，没时间。

**Comment by lzr2006** [comment]
其实我是想分发源码

**Comment by lzr2006** [comment]
我觉得那样更好些
