### ISSUE TITLE
wkgd.cf无法访问！

### ISSUE THREAD

**Issue by 2439905184** [lzr2006/lzr2006.github.io#4]
严重的小问题，wkgd.cf无法访问，域名过期了吗。

**Comment by 2439905184** [comment]
@lzr2006 ![Screenshot_20201216-212301.jpg](https://user-images.githubusercontent.com/29478722/102353995-e3179900-3fe4-11eb-8c07-c38c34e5ec63.jpg)

**Comment by lzr2006** [comment]
已完成域名修复，可访问`www.toysworld.ml`进入网页
